---
- hosts: test
  remote_user: ansible
  become: yes

  tasks:
  - name: install latest ntp
    yum:
      name: ntp
      state: latest
  - name: write ntp config file
    template:
      src: /ansible/templates/ntp.conf.j2
      dest: /etc/ntp.conf
  - name: ensure ntpd is running
    service:
      name: ntpd
      state: started
  handlers:
    - name: restart ntpd
      service:
        name: ntpd
        state: restarted
