---
- hosts: test
  remote_user: ansible
  become: yes

  tasks:
    - name: check if NetworkManager is running
      service:
        name: NetworkManager
        state: started
  tasks:
    - name: run echo command
      shell: /bin/echo $HOSTNAME
        dest: /hostname.txt
